### ISSUE TITLE
Error when configuring Slack notifications on macOS Sierra: "A keychain with the same name already exists."

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#555]
Here's what happens when I try to configure a Slack webhook URL in AutoPkgr 1.4.1 on Sierra.

> __A keychain with the same name already exists.__

I'm guessing this is exactly the same root cause as #554, but opening a separate issue just in case.

Screenshot:

<img width="532" alt="screen shot 2016-09-19 at 10 19 48 am" src="https://cloud.githubusercontent.com/assets/7801391/18641744/ca99c82e-7e52-11e6-9aae-542f0e3348f0.png">

Console output:

```
default	10:25:32.496075 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:32.496360 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:32.496824 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:32.497462 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:32.498457 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:32.499152 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:32.499385 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:32.499495 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:32.499728 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:32.499864 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:32.500028 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:32.500179 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:32.507815 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:32.507964 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:32.508131 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:32.508322 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:32.508562 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:32.508649 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:32.508773 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:32.508860 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:32.509063 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:32.509176 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:32.509319 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:32.509407 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:32.510473 -0700	com.lindegroup.AutoPkgr.helper	not switching as we're not in ~/Library/Keychains/: /Library/Keychains/System.keychain (0)
default	10:25:32.510534 -0700	com.lindegroup.AutoPkgr.helper	not switching as we're not in ~/Library/Keychains/: /Library/Keychains/System.keychain (0)
default	10:25:32.511049 -0700	com.lindegroup.AutoPkgr.helper	DbOpen of /private/var/db/mds/system/mdsObject.db
default	10:25:32.511283 -0700	com.lindegroup.AutoPkgr.helper	0x7fbaacc0b800 opened /private/var/db/mds/system/mdsObject.db: 4636 bytes
default	10:25:32.511387 -0700	com.lindegroup.AutoPkgr.helper	0x7fbaacc0b800 allocated /private/var/db/mds/system/mdsObject.db buffer 0x7fbaad806000 size 4636
default	10:25:32.511506 -0700	com.lindegroup.AutoPkgr.helper	0x7fbaacc0b800 closed /private/var/db/mds/system/mdsObject.db
default	10:25:32.512112 -0700	com.lindegroup.AutoPkgr.helper	DbOpen of /private/var/db/mds/system/mdsDirectory.db
default	10:25:32.512245 -0700	com.lindegroup.AutoPkgr.helper	0x7fbaacd1aa80 opened /private/var/db/mds/system/mdsDirectory.db: 50744 bytes
default	10:25:32.512331 -0700	com.lindegroup.AutoPkgr.helper	0x7fbaacd1aa80 allocated /private/var/db/mds/system/mdsDirectory.db buffer 0x7fbaad02c600 size 4
default	10:25:32.512421 -0700	com.lindegroup.AutoPkgr.helper	0x7fbaacd1aa80 closed /private/var/db/mds/system/mdsDirectory.db
default	10:25:32.512483 -0700	com.lindegroup.AutoPkgr.helper	0x7fbaacd1aa80 free /private/var/db/mds/system/mdsDirectory.db buffer 0x7fbaad02c600
default	10:25:32.513048 -0700	com.lindegroup.AutoPkgr.helper	0x7fbaacc0b800 free /private/var/db/mds/system/mdsObject.db buffer 0x7fbaad806000
default	10:25:32.513547 -0700	com.lindegroup.AutoPkgr.helper	DbOpen of /Library/Keychains/System.keychain
default	10:25:32.513885 -0700	com.lindegroup.AutoPkgr.helper	0x7fbaace0e970 opened /Library/Keychains/System.keychain: 35372 bytes
default	10:25:32.514069 -0700	com.lindegroup.AutoPkgr.helper	0x7fbaace0e970 allocated /Library/Keychains/System.keychain buffer 0x7fbaad810000 size 35372
default	10:25:32.514142 -0700	com.lindegroup.AutoPkgr.helper	0x7fbaace0e970 closed /Library/Keychains/System.keychain
default	10:25:32.517046 -0700	com.lindegroup.AutoPkgr.helper	loading /Library/Keychains/System.keychain
default	10:25:32.519902 -0700	com.lindegroup.AutoPkgr.helper	not attempting migration for /Library/Keychains/System.keychain version 256 (0 0 1)
default	10:25:32.520067 -0700	com.lindegroup.AutoPkgr.helper	keychain blob version does not support integrity
default	10:25:32.520127 -0700	com.lindegroup.AutoPkgr.helper	skipping integrity check due to keychain version
default	10:25:32.540942 -0700	AutoPkgr	not switching as we're not in ~/Library/Keychains/: /Library/Keychains/System.keychain (0)
default	10:25:32.543998 -0700	com.lindegroup.AutoPkgr.helper	not switching as we're not in ~/Library/Keychains/: /Library/Keychains/System.keychain (0)
default	10:25:32.547598 -0700	AutoPkgr	switching to keychain-db: /Users/linde/Library/Keychains/AutoPkgr.keychain-db from /Users/linde/Library/Keychains/AutoPkgr.keychain (1 1 0 1)
default	10:25:32.547676 -0700	AutoPkgr	switching to keychain-db: /Users/linde/Library/Keychains/AutoPkgr.keychain-db from /Users/linde/Library/Keychains/AutoPkgr.keychain-db (0 1 1 1)
default	10:25:32.548850 -0700	AutoPkgr	DbOpen of /var/folders/4w/sm7fv1cj3mjbr2p5p4z2b2sr0000gn/C//mds/mdsObject.db
default	10:25:32.548973 -0700	AutoPkgr	0x608002265d80 opened /var/folders/4w/sm7fv1cj3mjbr2p5p4z2b2sr0000gn/C//mds/mdsObject.db: 4636 bytes
default	10:25:32.549028 -0700	AutoPkgr	0x608002265d80 allocated /var/folders/4w/sm7fv1cj3mjbr2p5p4z2b2sr0000gn/C//mds/mdsObject.db buffer 0x7f8891841200 size 4636
default	10:25:32.549075 -0700	AutoPkgr	0x608002265d80 closed /var/folders/4w/sm7fv1cj3mjbr2p5p4z2b2sr0000gn/C//mds/mdsObject.db
default	10:25:32.549530 -0700	AutoPkgr	DbOpen of /var/folders/4w/sm7fv1cj3mjbr2p5p4z2b2sr0000gn/C//mds/mdsDirectory.db
default	10:25:32.549618 -0700	AutoPkgr	0x608001c7a8c0 opened /var/folders/4w/sm7fv1cj3mjbr2p5p4z2b2sr0000gn/C//mds/mdsDirectory.db: 50744 bytes
default	10:25:32.549687 -0700	AutoPkgr	0x608001c7a8c0 allocated /var/folders/4w/sm7fv1cj3mjbr2p5p4z2b2sr0000gn/C//mds/mdsDirectory.db buffer 0x7f8891acc800 size 4
default	10:25:32.549734 -0700	AutoPkgr	0x608001c7a8c0 closed /var/folders/4w/sm7fv1cj3mjbr2p5p4z2b2sr0000gn/C//mds/mdsDirectory.db
default	10:25:32.549772 -0700	AutoPkgr	0x608001c7a8c0 free /var/folders/4w/sm7fv1cj3mjbr2p5p4z2b2sr0000gn/C//mds/mdsDirectory.db buffer 0x7f8891acc800
default	10:25:32.549916 -0700	AutoPkgr	0x608002265d80 free /var/folders/4w/sm7fv1cj3mjbr2p5p4z2b2sr0000gn/C//mds/mdsObject.db buffer 0x7f8891841200
default	10:25:32.550097 -0700	AutoPkgr	DbCreate of /Users/linde/Library/Keychains/AutoPkgr.keychain-db
default	10:25:32.550202 -0700	AutoPkgr	open /Users/linde/Library/Keychains/AutoPkgr.keychain-db: File exists
default	10:25:32.550274 -0700	AutoPkgr	CSSM Exception: -2147413736 CSSMERR_DL_DATASTORE_ALREADY_EXISTS
default	10:25:32.550395 -0700	AutoPkgr	CSSM Exception: -2147413736 CSSMERR_DL_DATASTORE_ALREADY_EXISTS
default	10:25:32.550488 -0700	AutoPkgr	CSSM Exception: -2147413736 CSSMERR_DL_DATASTORE_ALREADY_EXISTS
default	10:25:33.784432 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:33.784534 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:33.784633 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:33.784696 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:33.784854 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:33.784924 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:33.785737 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:33.786253 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:33.786411 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:33.786487 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:33.786866 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:33.787077 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:33.799077 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:33.799267 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:33.799428 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:33.799754 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:33.800156 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:33.800398 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:33.800503 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:33.800866 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:33.801103 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:33.801250 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:33.801511 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:33.801584 -0700	com.lindegroup.AutoPkgr.helper	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	10:25:33.802814 -0700	com.lindegroup.AutoPkgr.helper	not switching as we're not in ~/Library/Keychains/: /Library/Keychains/System.keychain (0)
default	10:25:33.802891 -0700	com.lindegroup.AutoPkgr.helper	not switching as we're not in ~/Library/Keychains/: /Library/Keychains/System.keychain (0)
default	10:25:33.803218 -0700	com.lindegroup.AutoPkgr.helper	keychain blob version does not support integrity
default	10:25:33.803329 -0700	com.lindegroup.AutoPkgr.helper	skipping integrity check due to keychain version
default	10:25:33.817139 -0700	AutoPkgr	not switching as we're not in ~/Library/Keychains/: /Library/Keychains/System.keychain (0)
default	10:25:33.823110 -0700	com.lindegroup.AutoPkgr.helper	not switching as we're not in ~/Library/Keychains/: /Library/Keychains/System.keychain (0)
default	10:25:33.848721 -0700	AutoPkgr	switching to keychain-db: /Users/linde/Library/Keychains/AutoPkgr.keychain-db from /Users/linde/Library/Keychains/AutoPkgr.keychain (1 1 0 1)
default	10:25:33.848806 -0700	AutoPkgr	switching to keychain-db: /Users/linde/Library/Keychains/AutoPkgr.keychain-db from /Users/linde/Library/Keychains/AutoPkgr.keychain-db (0 1 1 1)
default	10:25:33.849061 -0700	AutoPkgr	DbCreate of /Users/linde/Library/Keychains/AutoPkgr.keychain-db
default	10:25:33.849195 -0700	AutoPkgr	open /Users/linde/Library/Keychains/AutoPkgr.keychain-db: File exists
default	10:25:33.849267 -0700	AutoPkgr	CSSM Exception: -2147413736 CSSMERR_DL_DATASTORE_ALREADY_EXISTS
default	10:25:33.849395 -0700	AutoPkgr	CSSM Exception: -2147413736 CSSMERR_DL_DATASTORE_ALREADY_EXISTS
default	10:25:33.849492 -0700	AutoPkgr	CSSM Exception: -2147413736 CSSMERR_DL_DATASTORE_ALREADY_EXISTS
```

**Comment by eahrold** [comment]
Should be fixed in this branch https://github.com/lindegroup/autopkgr/tree/feature/Sierra-Fixes

**Comment by homebysix** [comment]
Included in 1.4.2, just released.

**Comment by b3nnb** [comment]
im on the latest version of Autopkgr 0.6.1 and im getting this error still

**Comment by homebysix** [comment]
Hi @b3nnb — the latest version of AutoPkgr is 1.4.2.
