### ISSUE TITLE
New old problem

### ISSUE THREAD

**Issue by FuelEX** [lindegroup/autopkgr#606]
I'm trying to set up AutoPkgr using the JSSImporter tool.  I'm getting a Python error "No module named Requests" when trying to pull and repos.  It appears that I'm having the same issue as discussed here (https://github.com/lindegroup/autopkgr/issues/186) and here (https://github.com/sheagcraig/python-jss/pull/7) from back in 2014.  

I am also showing that AutoPkg is at 1.0.3 and has an update available.  When I click update it says successful, but then keeps the amber light next to it showing that there is an update available.  So, it appears that AutoPkg is crashing which is throwing the no module named requests error. 

I'm running AutoPkgr 1.4.2 (1375) on an iMac 27" with 10.13.2.  Jamf Pro is 10.0.0-t1508873342.  Any help would be greatly appreciated! 

Also, running a command via terminal gives me this:
autopkg run -v Firefox.jss
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 36, in <module>
    import autopkglib.github
  File "/Library/AutoPkg/autopkglib/__init__.py", line 629, in <module>
    import_processors()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 532, in import_processors
    mydirname + '.' + name, fromlist=[name]), name)
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 29, in <module>
    import jss
  File "/Library/Application Support/JSSImporter/jss/__init__.py", line 62, in <module>
    from .jamf_software_server import JSS
  File "/Library/Application Support/JSSImporter/jss/jamf_software_server.py", line 33, in <module>
    from . import jssobjects
  File "/Library/Application Support/JSSImporter/jss/jssobjects.py", line 27, in <module>
    import requests
ImportError: No module named requests

Thanks!!

**Comment by homebysix** [comment]
Hi @FuelEX - Can I have you try installing the latest JSSImporter, version 1.0.0 "Hammer Pants?" Aside from being a great name, it also uses `curl` instead of `requests`.

**Comment by FuelEX** [comment]
I ran the installer for this, restarted AutoPkgr and received the same error when trying to access a Repo.  It was showing JSSImporter 1.0.0 prior to the install as well, so I believe that I already had the latest version.

**Comment by SamHummerstone** [comment]
I am experiencing the exact same issue, and the installation of JSSImporter actually breaks AutoPKG for me too. Even though the update is said to use curl, it still seems to try and use requests (Which I have installed already, by the way).

**Comment by FuelEX** [comment]
So thankful that I'm not the only one!  Thanks for the validation Sam.

**Comment by jiggie914** [comment]
same here, 

Happy Holidays.. Dont code drunk lol

**Comment by homebysix** [comment]
Hi @SamHummerstone, @FuelEX, and @jiggie914 — Thanks for chiming in. Do you get errors only in AutoPkgr, or do the errors persist even when running recipes in Terminal?

Here's the command I usually test with:
```
/usr/bin/python /usr/local/bin/autopkg run --verbose --recipe-list ~/Library/Application\ Support/AutoPkgr/recipe_list.txt
```

**Comment by FuelEX** [comment]
This is what I get when running the command:

Yoda:~ eg061$ /usr/bin/python /usr/local/bin/autopkg run --verbose --recipe-list ~/Library/Application\ Support/AutoPkgr/recipe_list.txt
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 36, in <module>
    import autopkglib.github
  File "/Library/AutoPkg/autopkglib/__init__.py", line 629, in <module>
    import_processors()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 532, in import_processors
    mydirname + '.' + name, fromlist=[name]), name)
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 29, in <module>
    import jss
  File "/Library/Application Support/JSSImporter/jss/__init__.py", line 62, in <module>
    from .jamf_software_server import JSS
  File "/Library/Application Support/JSSImporter/jss/jamf_software_server.py", line 33, in <module>
    from . import jssobjects
  File "/Library/Application Support/JSSImporter/jss/jssobjects.py", line 27, in <module>
    import requests
ImportError: No module named requests

**Comment by SamHummerstoneCC** [comment]
Hi @homebysix ,

The errors persist even in the Terminal. I copied the command that you posted and it was successful when JSSImporter was uninstalled. On installation of JSSImporter, I received the error written in the main post.

**Comment by homebysix** [comment]
If the errors occur even in Terminal, then I suspect it's not an AutoPkgr-related issue. To be 100% sure, you'd need to do this on a test Mac:

1. Install AutoPkg
2. Install JSSImporter 1.0.0
3. Run a test JSS recipe

If the errors persist after those steps on a fresh Mac, then I'd recommend opening or continuing an issue on the [JSSImporter repo](https://github.com/sheagcraig/jssimporter).

**Comment by jiggie914** [comment]
I fixed the issue.
1.- Remove JSSImporter
2.- install JSSImporter from here https://github.com/sheagcraig/JSSImporter/releases/tag/v1.0.0
3.- It will show its out of date but now you can run the update from autopkgr
4.- update  Done then update your JSS info and test.

PS: i also did this and not sure if it helps..
sudo easy_install pip && pip install -I --user pyopenssl

so far no errors when installed that way.

**Comment by SamHummerstone** [comment]
Running everything in that order did not change anything for me, I am still receiving the `ImportError: No module named requests` error as before. The issue does seem to lie with JSSImporter.

**Comment by FuelEX** [comment]
I tried Jiggie's method and it still fails.

**Comment by xcutionr45** [comment]
I installed requests via `pip install requests` and I was able to get past the error. 
Now I have to play with it a bit more to see if it is able to import to Jamf Cloud DP.

**Comment by homebysix** [comment]
Ha... I forgot I actually proposed that solution long ago: https://groups.google.com/forum/#!msg/autopkgr-discuss/gM56bGTrgXU/52bfYoiTBgAJ

Can everyone else on the thread confirm that `pip install requests` resolves the issue?

**Comment by FuelEX** [comment]
Sudo pip install requests did resolve the issue for me, thanks everyone!

**Comment by homebysix** [comment]
Good to hear! I'm going to close this one.

**Comment by sumitphogat13** [comment]
I am having the same issue getting error No module named requests
When I run pip install requests getting below result
Requirement already satisfied: requests in ./Library/Python/3.7/lib/python/site-packages (2.21.0)

but when installing JSSimporter within AutoPKGr getting mentioned error
OS X : 10.12.6

**Comment by autopkg-bala04** [comment]
I'm getting the below error while running recipes—any suggestions.

autopkg run -vvv  MicrosoftExcel365.jamf     
Processing MicrosoftExcel365.jamf...
WARNING: /Users/rbi/Library/AutoPkg/RecipeRepos/com.github.autopkg.sebtomasi-recipes/PostProcessors/TeamsPoster.py: No module named 'requests'
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 1052, in get_processor
    _tmp = imp.load_source(processor_name, processor_filename)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/balaji/Library/AutoPkg/RecipeRepos/com.github.autopkg.sebtomasi-recipes/PostProcessors/TeamsPoster.py", line 19, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
  File "/Library/AutoPkg/autopkglib/__init__.py", line 1052, in get_processor
    _tmp = imp.load_source(processor_name, processor_filename)
Failed.
Receipt written to /tmp/receipts/MicrosoftExcel365-receipt-20220607-170012.plist

The following recipes failed:
    MicrosoftExcel365.jamf
        Unable to import 'com.github.sebtomasi.PostProcessors/TeamsPoster', likely due to syntax or Python error.

Nothing downloaded, packaged or imported.

**Comment by homebysix** [comment]
@autopkg-bala04 - This issue is unrelated to AutoPkgr. I would suggest opening an issue on the sebtomasi-recipes repo. There should be documentation for the TeamsPoster.py processor that clarifies that `requests` needs to be installed separately, since it's not included with AutoPkg.
